version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  labels:
  - dependencies
  groups:
    frontend-dependencies:
      patterns:
      - '*'
  reviewers:
  - jasmeralia
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  labels:
  - dependencies
  groups:
    python-test-dependencies:
      patterns:
      - '*'
  reviewers:
  - jasmeralia
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  labels:
  - dependencies
  groups:
    github-actions:
      patterns:
      - '*'
  reviewers:
  - jasmeralia